define markers_cluster before using it
markers_cluster is used by the JSON callback function.
We received by email the following report (Firefox 54 only):
> TypeError: markers_cluster is undefined sur map.js ligne 54

Although we don't have a reproducer, from a code perspective it may
possible if the JSON is returned quickly enough (ex: cached).
Moving markers_cluster definition earlier should make us safe against such a case.